; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Thu Nov 02 2023 14:22:42 GMT+0000 (Greenwich Mean Time)

