; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.4.0-LPC-STM32+7 on Thu Nov 02 2023 14:22:42 GMT+0000 (Greenwich Mean Time)
; Wait for set temperatures to be reached
M116 P0

